[package]
name = "succinct"
version = "0.5.3-alpha.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
description = "Succinct data structures for Rust"
repository = "https://github.com/tov/succinct-rs"
homepage = "https://github.com/tov/succinct-rs"
documentation = "https://docs.rs/succinct/"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["succinct", "rank", "select"]

[dependencies]
num-traits = "0.2"
byteorder = "1.2"
rkyv = "0.8.10"
serde = { version = "1.0.197", features = ["derive"] }

[dev-dependencies]
quickcheck = "0.9.0"
